### ISSUE TITLE
error importing

### ISSUE THREAD

**Issue by mvolkmann** [singhcool/deno-swagger-doc#8]
I tried importing this library with:

```js
import {swaggerDoc} from 'https://deno.land/x/deno_swagger_doc/mod.ts';
```

Just doing that in my code gives me the following errors when I run my server:

```text
error: TS2339 [ERROR]: Property 'parse' does not exist on type '{}'.
  parser.parse(swaggerObject, (err : any, api : any) => {
         ~~~~~
    at https://deno.land/x/deno_swagger_doc@releasev1.0.0/lib/helpers/finalizeSpecificationObject.ts:38:10

TS2339 [ERROR]: Property 'safeLoad' does not exist on type '{}'.
        swaggerJsDocComments.push(jsYaml.safeLoad(tag.description));
                                         ~~~~~~~~
    at https://deno.land/x/deno_swagger_doc@releasev1.0.0/lib/helpers/filterJsDocComments.ts:19:42

TS2339 [ERROR]: Property 'safeLoad' does not exist on type '{}'.
    yaml.push(jsYaml.safeLoad(fileContent));
                     ~~~~~~~~
    at https://deno.land/x/deno_swagger_doc@releasev1.0.0/lib/helpers/parseApiFileContent.ts:19:22

TS2339 [ERROR]: Property 'parse' does not exist on type '{}'.
        const jsDocComment = doctrine.parse(regexResults[i], { unwrap: true });
                                      ~~~~~
    at https://deno.land/x/deno_swagger_doc@releasev1.0.0/lib/helpers/parseApiFileContent.ts:24:39
```

**Comment by chansdad** [comment]
How do we resolve this error? Any suggestions?

**Comment by bramirez96** [comment]
Still having this issue, unfortunately! I don't know enough about the way the import system works in these Deno packages otherwise I'd go ahead and make a PR. I do love OpenAPI, though, and would love to see this implementation working!

**Comment by antonplagemann** [comment]
Just in case someone also encounters this:
You can try to add `--no-check` to the `deno run` command. This resolved the error in our project.

**Comment by singhcool** [comment]
HI @bramirez96 Just now we published the latest version. Please check it now.

**Comment by Marek00Malik** [comment]
I have the same problem, running with deno 1.16.4. 
`--no-check` nor `--unstable` does not help ;/
